owner: oklabflensburg
repo: open-health-check

sites:
  - name: Baumkataster Flensburg
    url: https://baumkataster-flensburg.de
    icon: https://baumkataster-flensburg.de/favicon.ico

  - name: Denkmalschutzliste Flensburg
    url: https://denkmalschutz-flensburg.de
    icon: https://denkmalschutz-flensburg.de/favicon.ico

  - name: Kommunalwahlkarte Schleswig-Holstein
    url: https://kommunalwahl-schleswig-holstein.de
    icon: https://kommunalwahl-schleswig-holstein.de/favicon.ico

  - name: Wahllokale Kommunalwahl Schleswig-Holstein
    url: https://wahllokale.kommunalwahl-schleswig-holstein.de
    icon: https://wahllokale.kommunalwahl-schleswig-holstein.de/favicon.ico

  - name: Luftdaten Schleswig-Holstein
    url: https://luftdaten.kunstbube.com
    icon: https://luftdaten.kunstbube.com/favicon.ico

  - name: Spielplatzkarte Flensburg
    url: https://spielplaetze.kunstbube.com
    icon: https://spielplaetze.kunstbube.com/favicon.ico

  - name: Website des OK Lab Flensburg
    url: https://oklabflensburg.de
    icon: https://oklabflensburg.de/favicon.ico

  - name: Daten Schnittstelle des OK Lab Flensburg
    url: https://api.oklabflensburg.de
    icon: https://api.oklabflensburg.de/favicon.ico

  - name: Bodennutzungskarte Deutschland
    url: https://bodennutzung.oklabflensburg.de
    icon: https://bodennutzung.oklabflensburg.de/favicon.ico

  - name: Nahverkehrskarte Flensburg
    url: https://nahverkehr.oklabflensburg.de
    icon: https://nahverkehr.oklabflensburg.de/favicon.ico

  - name: Recycling Standortkarte Flensburg
    url: https://recycling.oklabflensburg.de
    icon: https://recycling.oklabflensburg.de/favicon.ico

  - name: Sozialatlas Dashboard Flensburg
    url: https://sozialatlas.oklabflensburg.de
    icon: https://sozialatlas.oklabflensburg.de/favicon.ico

  - name: Sozialatlas Dashboard Flensburg (Alpha)
    url: https://dev.sozialatlas.oklabflensburg.de
    icon: https://dev.sozialatlas.oklabflensburg.de/favicon.ico

  - name: Website OK Lab Flensburg (Beta)
    url: https://website.oklabflensburg.de
    icon: https://website.oklabflensburg.de/favicon.ico

  - name: Unfallkarte Flensburg
    url: https://open-accident-map.de
    icon: https://open-accident-map.de/favicon.ico

  - name: Daten Schnittstelle Unfallkarte Flensburg
    url: https://api.open-accident-map.de
    icon: https://api.open-accident-map.de/favicon.ico

  - name: Sozialatlas Dashboard Flensburg (Beta)
    url: https://dev.sozialatlas-flensburg.de
    icon: https://dev.sozialatlas-flensburg.de/favicon.ico

status-website:
  name: Status OK Lab Flensburg
  cname: status.oklabflensburg.de
  baseurl: /
  logourl: https://codefor.de/labs/hexagon/CodeFor-flensburg.svg
  favicon: https://denkmalschutz-flensburg.de/favicon.ico
  robotsText: "User-agent: * \n Disallow: /"
  introMessage: "**OK Lab Flensburg** Gruppe von ehrenamtlich Aktiven, die sich für Offene Daten, Freie und Offene Software einsetzten"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
