owner: oklabflensburg
repo: open-health-check

sites:
  - name: Open Data Day Flensburg
    url: https://opendataday-flensburg.de
    icon: https://opendataday-flensburg.de/favicon.ico

  - name: Kitafinder Flensburg
    url: https://kitas-in-flensburg.de
    icon: https://kitas-in-flensburg.de/favicon.ico

  - name: Baumkataster Flensburg
    url: https://baumkataster-flensburg.de
    icon: https://baumkataster-flensburg.de/favicon.ico

  - name: Denkmalschutzliste Flensburg
    url: https://denkmalschutz-flensburg.de
    icon: https://denkmalschutz-flensburg.de/favicon.ico

  - name: Spielplatzkarte Flensburg
    url: https://spielplatzkarte.oklabflensburg.de
    icon: https://spielplatzkarte.oklabflensburg.de/favicon.ico

  - name: Website des OK Lab Flensburg
    url: https://oklabflensburg.de
    icon: https://oklabflensburg.de/favicon.ico

  - name: Daten Schnittstelle des OK Lab Flensburg
    url: https://api.oklabflensburg.de
    icon: https://api.oklabflensburg.de/static/favicon.ico

  - name: Schulen in Flensburg
    url: https://schulen-in-flensburg.de
    icon: https://schulen-in-flensburg.de/favicon.ico

  - name: Bodennutzungskarte Deutschland
    url: https://bodennutzung.oklabflensburg.de
    icon: https://bodennutzung.oklabflensburg.de/favicon.ico

  - name: Nahverkehrskarte Flensburg
    url: https://nahverkehr-flensburg.de
    icon: https://nahverkehr-flensburg.de/favicon.ico

  - name: Recycling Standortkarte Flensburg
    url: https://recycling.oklabflensburg.de
    icon: https://recycling.oklabflensburg.de/favicon.ico

  - name: Sozialatlas Dashboard Flensburg
    url: https://sozialatlas.oklabflensburg.de
    icon: https://sozialatlas.oklabflensburg.de/favicon.ico

  - name: Sozialatlas Dashboard Flensburg (Beta)
    url: https://dev.sozialatlas.oklabflensburg.de
    icon: https://dev.sozialatlas.oklabflensburg.de/favicon.ico

  - name: Website OK Lab Flensburg (Beta)
    url: https://website.oklabflensburg.de
    icon: https://website.oklabflensburg.de/favicon.ico

  - name: Unfallkarte Flensburg
    url: https://unfallkarte.oklabflensburg.de
    icon: https://unfallkarte.oklabflensburg.de/favicon.ico

  - name: Daten Schnittstelle Unfallkarte Flensburg
    url: https://api.oklabflensburg.de/accidents/v1/details
    icon: https://api.oklabflensburg.de/static/favicon.ico
    expectedStatusCodes:
      - 422

  - name: Sozialatlas Dashboard Flensburg (Alpha)
    url: https://dev.sozialatlas-flensburg.de
    icon: https://dev.sozialatlas-flensburg.de/favicon.ico

status-website:
  name: Status OK Lab Flensburg
  cname: status.oklabflensburg.de
  baseurl: /
  logourl: https://codefor.de/labs/hexagon/CodeFor-flensburg.svg
  favicon: https://denkmalschutz-flensburg.de/favicon.ico
  robotsText: "User-agent: * \n Disallow: /"
  introMessage: "**OK Lab Flensburg** Gruppe von ehrenamtlich Aktiven, die sich für Offene Daten, Freie und Offene Software einsetzten"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
